### ISSUE TITLE
Race Condition with Measurements and Signal Handling

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/power-gadget_benchexec#2]
A signal could interrupt the measurement code and thus the measurement is not atomic, leading to possibly slightly wrong results.

We should replace the use of a signal handler and `usleep` with `sigtimedwait`, which allows us to have a single loop that handles both the signals and the measurement.

**Comment by leostrakosch** [comment]
Should be resolved by commit 62647c28 .
